accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = "accounts"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

multiplayer/urls.py
from django.urls import path

from . import views

app_name = "multiplayer"
urlpatterns = [
    path("", views.lobby, name="lobby"),
    path("test/", views.test, name="test"),
    path("create/", views.create, name="create"),
    path("join/<str:game_id>/", views.join, name="join"),
    path("<str:game_id>/", views.game, name="game"),
]

onitama/urls.py
from django.contrib import admin
from django.urls import path, include
from singleplayer.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('singleplayer/', include("singleplayer.urls")),
    path('multiplayer/', include("multiplayer.urls")),
    path("accounts/", include("accounts.urls", "accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
]

singleplayer/urls.py
from django.urls import path
from . import views

app_name = "singleplayer"
urlpatterns = [
    path("", views.home, name="home"),
    path("game/", views.game, name="game"),
    path("game/move/", views.user_move, name="move"),
    path("game/setup/", views.setup, name="setup"),
    path("game/AIsettings/", views.AIsettings, name="AIsettings")
]

multiplayer/models.py
from django.db import models
from accounts.models import OnitamaUser
import uuid

class MultiplayerGame(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(OnitamaUser, on_delete=models.CASCADE,related_name="owner")
    opponent = models.ForeignKey(OnitamaUser, on_delete=models.CASCADE,related_name="opponent", null=True)
    owner_color= models.CharField(max_length=10)
    owner_online = models.BooleanField(default=False)
    opponent_online = models.BooleanField(default=False)
    winner = models.CharField(max_length=20, null=True, blank=True)
    CHOICES=(
        (1,"Created"),
        (2,"Started"),
        (3,"Ended"))
    status = models.IntegerField(default=1,choices=CHOICES)

    def setWinner(self, winner):
        self.status = 3
        self.winner = winner
        k = 32

        if winner == "owner":
            winningUser = self.owner
            losingUser = self.opponent
        else:
            winningUser = self.opponent
            losingUser = self.owner
        
        winningProbability = 1 / ( 1 + 10 ** ((losingUser.rating - winningUser.rating) / 400) )
        winningUser.rating += round(k * ( 1 - winningProbability))

        losingProbability = 1 / ( 1 + 10 ** ((winningUser.rating - losingUser.rating) / 400) )
        losingUser.rating += round(k * ( 0 - losingProbability))

        winningUser.save()
        losingUser.save()        
        self.save()

multiplayer/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import MultiplayerGame
from .models import OnitamaUser
import random

@login_required
def lobby(request):
    return render(request, "multiplayer/lobby.html", {
        "games": MultiplayerGame.objects.filter(status=1),
        "leaders": OnitamaUser.objects.all().order_by('-rating').values()[0:5]
    })

def test(request):
    return render(request, "multiplayer/designtest.html")

def room(request, room_name):
    return render(request, "multiplayer/room.html", {"room_name": room_name})

@login_required
def game(request, game_id):
    game = MultiplayerGame.objects.get(pk=game_id)
    colors = ["red", "blue"]
    username = request.user.username
    rating = request.user.rating
    if request.user == game.owner:
        is_owner = "true"
        user_color = game.owner_color
        colors.remove(user_color)
        opponent_color = colors[0]
    else:
        is_owner = "false"
        opponent_color = game.owner_color
        colors.remove(opponent_color)
        user_color = colors[0]
        
    return render(request, "multiplayer/game.html", 
                  {"game_id": game_id, 
                   "user_color": user_color,
                   "opponent_color": opponent_color,
                   "is_owner": is_owner,
                   "username": username,
                   "rating": rating})

@login_required
def create(request):
    color = random.choice(["red", "blue"])
    game = MultiplayerGame(owner=request.user, owner_color=color)
    game.save()
    return HttpResponseRedirect(reverse("multiplayer:game", args=(game.id,)))

@login_required
def join(request, game_id):
    game = MultiplayerGame.objects.get(pk=game_id)
    if (game.owner == request.user or game.opponent == request.user):
        return HttpResponseRedirect(reverse("multiplayer:game", args=(game.id,)))
    if (game.opponent is not None):
        return HttpResponseRedirect(reverse("index"))
    
    game.opponent = request.user
    game.save()
    return HttpResponseRedirect(reverse("multiplayer:game", args=(game.id,)))


    

multiplayer/templates/multiplayer/game copy.html
<!DOCTYPE html>
{% load static %}
{% csrf_token %}



<html lang="en">
    <head>
        <title>Onitama</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
        <link rel="stylesheet" href="{% static 'onitama-styling.css' %}">
        <script>
            const userColor = "{{ user_color }}";
            const opponentColor = "{{ opponent_color }}";
            const gameId = "{{ game_id }}";
            const isOwner = "{{ is_owner}}" === "true";
        </script>
        <script src="{% static 'front-end/multiplayer.js' %}"></script>
    </head>
    <body>
        <div id="wrapper">
            <div class="game-space">
                <div class="board"></div>
            </div>
        </div>
    </body>
</html>


<!-- {{ game_id|json_script:"game-id" }} {# makes the room name accesible for javascript via json object #}
{{ color|json_script:"user-color" }} -->
<!-- basic DOM setup script modified from singleplayer -->
<!-- <script>

    const selectionState = {
        source: null,
        target: null,
    }

    function clickedSpace(e) {
        if (selectionState.source == null) {
            selectionState.source = e.currentTarget;
            return;
        }
        if (selectionState.target == null) {
            selectionState.target = e.currentTarget;
        }
        console.log(selectionState);
        chatSocket.send(JSON.stringify({
            'color': userColor,
            'source': selectionState.source.id,
            'target': selectionState.target.id,
        }));
        selectionState.source = null;
        selectionState.target = null;
        return;
    };

    function getPawnElement(space) {
        return document.getElementById(space.id).querySelector(".pawn");
    };

    function movePawn(source, destination) {
        getPawnElement(destination).className = getPawnElement(source).className;
        getPawnElement(source).className = "pawn pawn-empty";
        return;
    };

    function mirror(spaceId) {
        var row = parseInt(spaceId[0]);
        var col = parseInt(spaceId[1]);
        row = 4 - row;
        col = 4 - col;
        return row.toString() + col.toString();
    }

    // basic DOM building and spaces/pieces    

    document.addEventListener('DOMContentLoaded', () => {
        const userColor = JSON.parse(document.getElementById('user-color').textContent);
        var otherColor = 'red';
        console.log(userColor == 'red')
        if (userColor == 'red') {
            otherColor = 'blue';
        }

        var board = document.getElementsByClassName("board")[0];

        // create the spaces
        for (let i = 0; i < 5; i++) {
            for (let j = 0; j < 5; j++) {
                let space = document.createElement("div");
                space.setAttribute("class", "space");
                space.setAttribute("id", `${i}${j}`);
                // space.style.backgroundImage = `url(images/spaces/${i}${j}.png`;
                space.onclick = clickedSpace;
                board.appendChild(space);

                // let selection_element = document.createElement("div");
                // selection_element.classList.add("selection");
                // selection_element.classList.add("selection-empty");
                // space.appendChild(selection_element);

                let pawn_element = document.createElement("div");
                pawn_element.classList.add("pawn");
                pawn_element.classList.add("pawn-empty");
                space.appendChild(pawn_element);
            }
        }


        // create the top pieces
        for (let i = 0; i < 5; i++) {
            let space = document.getElementById(`0${i}`);
            if (i == 2) {
                space.querySelector(".pawn").classList.remove("pawn-empty");
                space.querySelector(".pawn").classList.add(`pawn-${otherColor}-master`);
                var top_temple = document.createElement("div");
                top_temple.classList.add(`${otherColor}-temple`);
                space.appendChild(top_temple);
            }
            else {
                space.querySelector(".pawn").classList.remove("pawn-empty");
                space.querySelector(".pawn").classList.add(`pawn-${otherColor}-normal`);
            }
        }

        // create the bottom pieces
        for (let i = 0; i < 5; i++) {
            let space = document.getElementById(`4${i}`);
            if (i == 2) {
                space.querySelector(".pawn").classList.remove("pawn-empty");
                space.querySelector(".pawn").classList.add(`pawn-${userColor}-master`);
                var bottom_temple = document.createElement("div");
                bottom_temple.classList.add(`${userColor}-temple`);
                space.appendChild(bottom_temple);
            }
            else {
                space.querySelector(".pawn").classList.remove("pawn-empty");
                space.querySelector(".pawn").classList.add(`pawn-${userColor}-normal`);
            }
        }
    });







    // NEW TESTING FOR CHANNELS
    const gameId = JSON.parse(document.getElementById('game-id').textContent);
    const userColor = JSON.parse(document.getElementById('user-color').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/multiplayer/'
        + gameId
        + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        console.log(data);
        var color = data['color'];
        var sourceId = data['source'];
        var targetId = data['target'];
        if (color != userColor) {
            sourceId = mirror(sourceId);
            targetId = mirror(targetId);
        }
        source = document.getElementById(sourceId);
        target = document.getElementById(targetId);

        movePawn(source, target);
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };


</script> -->

multiplayer/templates/multiplayer/game copy2.html
<!DOCTYPE html>
{% load static %}
{% csrf_token %}



<html lang="en">
    <head>
        <title>Onitama</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
        <link rel="stylesheet" href="{% static 'onitama-styling.css' %}">
        <script>
            var static_url = "{% get_static_prefix %}";
            const userColor = "{{ user_color }}";
            const opponentColor = "{{ opponent_color }}";
            const gameId = "{{ game_id }}";
            const isOwner = "{{ is_owner}}" === "true";
            const userName = "{{ username}}"
        </script>
        <script src="{% static 'front-end/cards.js' %}"></script>
        <script src="{% static 'front-end/multiplayer.js' %}"></script>
    </head>
    <body>
        <div id="wrapper">
            <div class="player-hand">
                <div class="card rotated" id="opponent_card_0"></div>
                <div class="card rotated" id="opponent_card_1"></div>
            </div>
            <div class="game-space">
                <div class="card middle rotated" id="middle_card_0"></div>
                <div class="board"></div>
                <div class="card middle" id="middle_card_1"></div>
            </div>
            <div class="player-hand">
                <div class="card user-card" id="user_card_0">
                    <div class="selection-card-empty"></div>
                </div>
                <div class="card user-card" id="user_card_1">
                    <div class="selection-card-empty"></div>
                </div>
            </div>
        </div>
        <div class="sidebar">
            <a href="{% url 'singleplayer:home' %}">Home</a>
            <br>
            <a href="{% url 'singleplayer:game' %}">Singleplayer</a>
            <br>
            <a href="{% url 'multiplayer:lobby' %}">Multiplayer</a>
            <br>
            <br>
            <br>
            <div class="vs-summary">
                <p id="opponent-tag" class = "username"></p>
                <p id="vs">Waiting for opponent</p>
                <p id="user-tag" class = "username"></p>
            </div>
        </div>
    </body>
</html>





<!-- {{ game_id|json_script:"game-id" }} {# makes the room name accesible for javascript via json object #}
{{ color|json_script:"user-color" }} -->
<!-- basic DOM setup script modified from singleplayer -->
<!-- <script>

    const selectionState = {
        source: null,
        target: null,
    }

    function clickedSpace(e) {
        if (selectionState.source == null) {
            selectionState.source = e.currentTarget;
            return;
        }
        if (selectionState.target == null) {
            selectionState.target = e.currentTarget;
        }
        console.log(selectionState);
        chatSocket.send(JSON.stringify({
            'color': userColor,
            'source': selectionState.source.id,
            'target': selectionState.target.id,
        }));
        selectionState.source = null;
        selectionState.target = null;
        return;
    };

    function getPawnElement(space) {
        return document.getElementById(space.id).querySelector(".pawn");
    };

    function movePawn(source, destination) {
        getPawnElement(destination).className = getPawnElement(source).className;
        getPawnElement(source).className = "pawn pawn-empty";
        return;
    };

    function mirror(spaceId) {
        var row = parseInt(spaceId[0]);
        var col = parseInt(spaceId[1]);
        row = 4 - row;
        col = 4 - col;
        return row.toString() + col.toString();
    }

    // basic DOM building and spaces/pieces    

    document.addEventListener('DOMContentLoaded', () => {
        const userColor = JSON.parse(document.getElementById('user-color').textContent);
        var otherColor = 'red';
        console.log(userColor == 'red')
        if (userColor == 'red') {
            otherColor = 'blue';
        }

        var board = document.getElementsByClassName("board")[0];

        // create the spaces
        for (let i = 0; i < 5; i++) {
            for (let j = 0; j < 5; j++) {
                let space = document.createElement("div");
                space.setAttribute("class", "space");
                space.setAttribute("id", `${i}${j}`);
                // space.style.backgroundImage = `url(images/spaces/${i}${j}.png`;
                space.onclick = clickedSpace;
                board.appendChild(space);

                // let selection_element = document.createElement("div");
                // selection_element.classList.add("selection");
                // selection_element.classList.add("selection-empty");
                // space.appendChild(selection_element);

                let pawn_element = document.createElement("div");
                pawn_element.classList.add("pawn");
                pawn_element.classList.add("pawn-empty");
                space.appendChild(pawn_element);
            }
        }


        // create the top pieces
        for (let i = 0; i < 5; i++) {
            let space = document.getElementById(`0${i}`);
            if (i == 2) {
                space.querySelector(".pawn").classList.remove("pawn-empty");
                space.querySelector(".pawn").classList.add(`pawn-${otherColor}-master`);
                var top_temple = document.createElement("div");
                top_temple.classList.add(`${otherColor}-temple`);
                space.appendChild(top_temple);
            }
            else {
                space.querySelector(".pawn").classList.remove("pawn-empty");
                space.querySelector(".pawn").classList.add(`pawn-${otherColor}-normal`);
            }
        }

        // create the bottom pieces
        for (let i = 0; i < 5; i++) {
            let space = document.getElementById(`4${i}`);
            if (i == 2) {
                space.querySelector(".pawn").classList.remove("pawn-empty");
                space.querySelector(".pawn").classList.add(`pawn-${userColor}-master`);
                var bottom_temple = document.createElement("div");
                bottom_temple.classList.add(`${userColor}-temple`);
                space.appendChild(bottom_temple);
            }
            else {
                space.querySelector(".pawn").classList.remove("pawn-empty");
                space.querySelector(".pawn").classList.add(`pawn-${userColor}-normal`);
            }
        }
    });







    // NEW TESTING FOR CHANNELS
    const gameId = JSON.parse(document.getElementById('game-id').textContent);
    const userColor = JSON.parse(document.getElementById('user-color').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/multiplayer/'
        + gameId
        + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        console.log(data);
        var color = data['color'];
        var sourceId = data['source'];
        var targetId = data['target'];
        if (color != userColor) {
            sourceId = mirror(sourceId);
            targetId = mirror(targetId);
        }
        source = document.getElementById(sourceId);
        target = document.getElementById(targetId);

        movePawn(source, target);
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };


</script> -->

multiplayer/templates/multiplayer/game.html
<!DOCTYPE html>
{% load static %}
{% csrf_token %}

<html lang="en">
    <head>
        <title>Waiting for opponent | Play-Onitama.com</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700;900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
        <link rel="stylesheet" href="{% static 'design-test.css' %}">
        <script>
            const userColor = "{{ user_color }}";
            const opponentColor = "{{ opponent_color }}";
            const gameId = "{{ game_id }}";
            const isOwner = "{{ is_owner }}" === "true";
            const userName = "{{ username }}";
            const rating = "{{ rating }}";
        </script>
        <script src="{% static 'front-end/cards.js' %}"></script>
        <script src="{% static 'front-end/designtest.js' %}"></script>
    </head>
    <body>
        <div class="sidebar sidebar-left">
            <ul class="page-links">
                <li class="logo"><a href="{% url 'home' %}">Onitama</a></li>
                <li><a href="{% url 'singleplayer:game' %}">Singleplayer</a></li>
                <li><a href="{% url 'multiplayer:lobby' %}">Multiplayer</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div> 
        <div class="game-space">
            <div id="results" class="inactive">
                <div></div>
                <button type="button">Close</button>
            </div>
            <div class="card-hand">
                <div id="opponent_card_0" class="card nonempty rotated"></div>
                <div id="opponent_card_1" class="card nonempty rotated"></div>
            </div>
            <div class="board-space">
                <div id="middle_card_0" class="card rotated"></div>
                <div id="board" class="board">
                    <div id="00" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ opponent_color }}-normal"></div>
                    </div>
                    <div id="01" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ opponent_color }}-normal"></div>
                    </div>
                    <div id="02" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ opponent_color }}-master"></div>
                        <div class="temple opponent rotated {{ opponent_color }}"></div>
                    </div>
                    <div id="03" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ opponent_color }}-normal"></div>
                    </div>
                    <div id="04" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ opponent_color }}-normal"></div>
                    </div>
                    <div id="10" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="11" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="12" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="13" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="14" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="20" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="21" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="22" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="23" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="24" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="30" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="31" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="32" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="33" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="34" class="space">
                        <div class="selection"></div>
                        <div class="pawn"></div>
                    </div>
                    <div id="40" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ user_color }}-normal"></div>
                    </div>
                    <div id="41" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ user_color }}-normal"></div>
                    </div>
                    <div id="42" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ user_color }}-master"></div>
                        <div class="temple user {{ user_color }}"></div>
                    </div>
                    <div id="43" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ user_color }}-normal"></div>
                    </div>
                    <div id="44" class="space">
                        <div class="selection"></div>
                        <div class="pawn nonempty {{ user_color }}-normal"></div>
                    </div>                    
                </div>
                <div id="middle_card_1" class="card"></div>
            </div>
            <div class="card-hand">
                <div id="user_card_0" class="card nonempty">
                    <div class="selection"></div>
                </div>
                <div id="user_card_1" class="card nonempty">
                    <div class="selection"></div>
                </div>
            </div>
        </div>
        <div class="sidebar sidebar-right">
            <div id="opponent-info" class="user active">
                <img class="color-icon" src="/static/images/testing/{{ opponent_color }}-icon.png">
                <div class="name">Waiting for</div>
                <div class="rating">opponent...</div>
            </div>
            <div id="chat" class="chat">Chat coming soon...</div>
            <div id="game-history" class="game-history">
                <img id="step_backward" class="step" src="/static/images/testing/step.png">
                <img id="step_forward" class="step" src="/static/images/testing/step.png">
            </div>
            <div id="user-info" class="user">
                <img class="color-icon" src="/static/images/testing/{{ user_color }}-icon.png">
                <div class="name">{{ username }}</div>
                <div class="rating">({{ rating }})</div>
            </div>
        </div>
    </body>
</html>

multiplayer/templates/multiplayer/lobby.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Lobby | Play-Onitama.com</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700;900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
    <link rel="stylesheet" href="{% static 'design-test.css' %}">
</head>
<body>
    <div class="sidebar sidebar-left">
        <ul class="page-links">
            <li class="logo"><a href="{% url 'home' %}">Onitama</a></li>
            <li><a href="{% url 'singleplayer:game' %}">Singleplayer</a></li>
            <li><a href="{% url 'multiplayer:lobby' %}">Multiplayer</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
            <div id="user-info" class="user history-standby">
                <img class="color-icon" src="/static/images/testing/grey-icon.png">
                <div class="name">{{ user.username }}</div>
                <div class="rating">({{ user.rating }})</div>
            </div>
        {% endif %}
    </div>
    <div class="lobby-space">
        <div class="logo">Multiplayer</div>
        <div class="open-games">
            <header>Open Games</header>
            <ul>
                {% for game in games %}
                <li>
                    <a href="{% url 'multiplayer:join' game_id=game.id %}">vs. {{ game.owner }}
                        <img class="open-game-color" src="/static/images/testing/{{ game.owner_color }}-icon.png">
                    </a>
                </li>
                {% empty %}
                <br>
                <div class="empty-message">There are no open games to join.</div>
                <br>
                <div class="empty-message"><a href="{% url 'multiplayer:create' %}">Create</a> a game for an opponent to join or play against the computer in <a href="{% url 'singleplayer:game' %}">singleplayer</a>.</div>
                {% endfor %}
            </ul>
        </div>
        <a class="create-game" href="{% url 'multiplayer:create' %}"><div>Create Game</div></a>
        <div class="leaderboard">
            <header>Leaderboard</header>
            <ol>
                <li style="padding-left: .2em">1. {{ leaders.0.username }} ({{ leaders.0.rating }})</li>
                <li>2. {{ leaders.1.username }} ({{ leaders.1.rating }})</li>
                <li>3. {{ leaders.2.username }} ({{ leaders.2.rating }})</li>
                <li>4. {{ leaders.3.username }} ({{ leaders.3.rating }})</li>
                <li>5. {{ leaders.4.username }} ({{ leaders.4.rating }})</li>
            </ol>
        </div>
    </div>
</body>
</html>


<!-- <h2>Open Games</h2>
    <ul>
        {% for game in games %}
            <li>Game {{ game.id }}: {{ game.owner }} playing {{ game.opponent }}</li>
        {% endfor %}
    </ul>

    <br>
    <a href="{% url 'multiplayer:create' %}">Create a Game</a>

    <ul>
        {% for game in games %}
            <li>
                <a href="{% url 'multiplayer:join' game_id=game.id %}">Game {{ game.id }}: {{ game.owner }} playing {{ game.opponent }}</a>
            </li>
        {% endfor %}
    </ul> -->